# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the website › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-paginate configuration
paginate: 10

# The title of your site
title: Tech Diary

# The tagline for your site
tagline:  aaa hi gaye ho to seekh ke jao kuch
# The description of your site (for SEO)
description: >-
  A technical diary and learning journal where I document my programming experiences,
  discoveries, and lessons learned in software development.

# Replace with your domain, e.g., 'https://username.github.io'
# For GitHub Pages, use: https://yourusername.github.io/repository-name
url: "https://UmerFruit.github.io"

# GitHub information
github:
  username: UmerFruit

# Social media links (optional - customize as needed)
social:
  # Change to your full name.
  name: Umer Farooq
  email: umerfarooq1105@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/UmerFruit # change to your GitHub homepage
    - https://www.linkedin.com/in/username


theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: '/assets/img/avatar.jpg'

# boolean type, the global switch for TOC in posts.
toc: true

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: '' # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - docs
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# GitHub Pages compatible plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
